M48
; DRILL file {KiCad 9.0.6-9.0.6~ubuntu24.04.1} date 2026-01-11T19:57:41-0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-11T19:57:41-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6-9.0.6~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.800
%
G90
G05
T1
X246.325Y-176.897
T2
X177.525Y-176.897
T3
X176.9Y-83.272
X242.5Y-83.272
M30
